# See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

# Workflow name
name: Run Test

# Run on event push
on: push

jobs:

  #
  # Job build-1-16
  # Build on AlmaLinux 8.5 using golang version 1.16
  #
  build-1-16:
    runs-on: ubuntu-latest
    container: almalinux@8.5
    steps:
    # See: https://github.com/marketplace/actions/checkout
    # Checkout git repository and submodules
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    # See: https://github.com/marketplace/actions/setup-go-environment
    - name: Setup Golang
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.7'

    # Install libganglia
    - name: Setup Ganglia
      run: sudo apt install ganglia-monitor libganglia1

    - name: Build MetricCollector
      run: make

    - name: Run MetricCollector once
      run: ./cc-metric-collector --once --config .github/ci-config.json
