# See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

# Workflow name
name: AlmaLinux 8.5 RPM build

# Run on event push
on: push

jobs:

  #
  # Build on AlmaLinux 8.5 using golang version 1.16
  #
  AlmaLinux-RPM-build:
    runs-on: ubuntu-latest
    container: almalinux:8.5
    steps:

    # Use dnf to install required dependencies
    - name: Install dependencies
      run: |
        dnf --assumeyes group install "Development Tools" "RPM Development Tools"
        dnf --assumeyes       install wget

    # Checkout git repository and submodules
    # fetch-depth must be 0 to use git describe
    # See: https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    # See: https://github.com/marketplace/actions/setup-go-environment
    - name: Setup Golang
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.7'

    - name: RPM build MetricCollector
      id: rpmbuild
      run: |
        make RPM
        RPM=~/rpmbuild/RPMS/*/*.rpm
        SRPM=~/rpmbuild/SRPMS/*.src.rpm
        echo ::set-output name="SRPM::${SRPM}"
        echo ::set-output name="RPM::${RPM}"

    # See: https://github.com/actions/upload-artifact
    - name: Save RPM as artifact
      uses: actions/upload-artifact@v2
      with:
        name: cc-metric-collector RPM AlmaLinux 8.5
        path: ${{ steps.rpmbuild.outputs.RPM }}
    - name: Save SRPM as artifact
      uses: actions/upload-artifact@v2
      with:
        name: cc-metric-collector SRPM AlmaLinux 8.5
        path: ${{ steps.rpmbuild.outputs.SRPM }}

    # See: https://github.com/softprops/action-gh-release
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: cc-metric-collector-${{github.ref_name}}
        files: |
         ${{ steps.rpmbuild.outputs.RPM }}
         ${{ steps.rpmbuild.outputs.SRPM }}